<?php
/**
 * Created by PhpStorm.
 * User: BrunaRocha
 * Date: 18/10/2019
 * Time: 09:45
 */

return [
    'text_diretor'       => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse placerat quam ac volutpat bibendum. Ut augue dolor, dapibus eu euismod vel, fringilla sed dolor. Quisque ullamcorper dapibus dolor ac malesuada. Aenean efficitur placerat feugiat. Vivamus in dolor neque. Duis at ipsum eget mi maximus auctor. Quisque ac mi eros. Sed sit amet tortor non odio mollis fringilla vitae ut sem. Maecenas nec ante et leo ullamcorper tempus. Suspendisse potenti. Praesent nec ornare quam. Etiam fringilla hendrerit nulla. Proin fermentum finibus dui ut dapibus. Aliquam mattis interdum lacus, nec interdum justo interdum ut. Aliquam sagittis turpis eu magna egestas, et placerat arcu aliquet. In vel feugiat dolor. Quisque efficitur tristique ligula ut dictum. Aenean consectetur nunc a turpis vestibulum semper. Donec non ultricies ligula, non suscipit felis. Aenean vel orci ultrices metus scelerisque sagittis ut eu massa. Pellentesque consectetur, ex scelerisque porttitor volutpat, felis neque aliquet sapien, tristique efficitur arcu enim luctus enim.',
    'text_cursos_livres' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse placerat quam ac volutpat bibendum. Ut augue dolor, dapibus eu euismod vel, fringilla sed dolor. Quisque ullamcorper dapibus dolor ac malesuada. Aenean efficitur placerat feugiat. Vivamus in dolor neque. Duis at ipsum eget mi maximus auctor. Quisque ac mi eros. Sed sit amet tortor non odio mollis fringilla vitae ut sem. Maecenas nec ante et leo ullamcorper tempus. Suspendisse potenti. Praesent nec ornare quam. Etiam fringilla hendrerit nulla. Proin fermentum finibus dui ut dapibus. Aliquam mattis interdum lacus, nec interdum justo interdum ut. Aliquam sagittis turpis eu magna egestas, et placerat arcu aliquet. In vel feugiat dolor. Quisque efficitur tristique ligula ut dictum. Aenean consectetur nunc a turpis vestibulum semper. Donec non ultricies ligula, non suscipit felis. Aenean vel orci ultrices metus scelerisque sagittis ut eu massa. Pellentesque consectetur, ex scelerisque porttitor volutpat, felis neque aliquet sapien, tristique efficitur arcu enim luctus enim.',
    'text_consultoria'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse placerat quam ac volutpat bibendum. Ut augue dolor, dapibus eu euismod vel, fringilla sed dolor. Quisque ullamcorper dapibus dolor ac malesuada. Aenean efficitur placerat feugiat. Vivamus in dolor neque. Duis at ipsum eget mi maximus auctor. Quisque ac mi eros. Sed sit amet tortor non odio mollis fringilla vitae ut sem. Maecenas nec ante et leo ullamcorper tempus. Suspendisse potenti. Praesent nec ornare quam. Etiam fringilla hendrerit nulla. Proin fermentum finibus dui ut dapibus. Aliquam mattis interdum lacus, nec interdum justo interdum ut. Aliquam sagittis turpis eu magna egestas, et placerat arcu aliquet. In vel feugiat dolor. Quisque efficitur tristique ligula ut dictum. Aenean consectetur nunc a turpis vestibulum semper. Donec non ultricies ligula, non suscipit felis. Aenean vel orci ultrices metus scelerisque sagittis ut eu massa. Pellentesque consectetur, ex scelerisque porttitor volutpat, felis neque aliquet sapien, tristique efficitur arcu enim luctus enim.',
    'text_publicacao'    => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse placerat quam ac volutpat bibendum. Ut augue dolor, dapibus eu euismod vel, fringilla sed dolor. Quisque ullamcorper dapibus dolor ac malesuada. Aenean efficitur placerat feugiat. Vivamus in dolor neque. Duis at ipsum eget mi maximus auctor. Quisque ac mi eros. Sed sit amet tortor non odio mollis fringilla vitae ut sem. Maecenas nec ante et leo ullamcorper tempus. Suspendisse potenti. Praesent nec ornare quam. Etiam fringilla hendrerit nulla. Proin fermentum finibus dui ut dapibus. Aliquam mattis interdum lacus, nec interdum justo interdum ut. Aliquam sagittis turpis eu magna egestas, et placerat arcu aliquet. In vel feugiat dolor. Quisque efficitur tristique ligula ut dictum. Aenean consectetur nunc a turpis vestibulum semper. Donec non ultricies ligula, non suscipit felis. Aenean vel orci ultrices metus scelerisque sagittis ut eu massa. Pellentesque consectetur, ex scelerisque porttitor volutpat, felis neque aliquet sapien, tristique efficitur arcu enim luctus enim.',
    'text_clientes'      => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse placerat quam ac volutpat bibendum. Ut augue dolor, dapibus eu euismod vel, fringilla sed dolor. Quisque ullamcorper dapibus dolor ac malesuada. Aenean efficitur placerat feugiat. Vivamus in dolor neque. Duis at ipsum eget mi maximus auctor. Quisque ac mi eros. Sed sit amet tortor non odio mollis fringilla vitae ut sem. Maecenas nec ante et leo ullamcorper tempus. Suspendisse potenti. Praesent nec ornare quam. Etiam fringilla hendrerit nulla. Proin fermentum finibus dui ut dapibus. Aliquam mattis interdum lacus, nec interdum justo interdum ut. Aliquam sagittis turpis eu magna egestas, et placerat arcu aliquet. In vel feugiat dolor. Quisque efficitur tristique ligula ut dictum. Aenean consectetur nunc a turpis vestibulum semper. Donec non ultricies ligula, non suscipit felis. Aenean vel orci ultrices metus scelerisque sagittis ut eu massa. Pellentesque consectetur, ex scelerisque porttitor volutpat, felis neque aliquet sapien, tristique efficitur arcu enim luctus enim.',
    'text_contato'       => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse placerat quam ac volutpat bibendum. Ut augue dolor, dapibus eu euismod vel, fringilla sed dolor. Quisque ullamcorper dapibus dolor ac malesuada. Aenean efficitur placerat feugiat. Vivamus in dolor neque. Duis at ipsum eget mi maximus auctor. Quisque ac mi eros. Sed sit amet tortor non odio mollis fringilla vitae ut sem. Maecenas nec ante et leo ullamcorper tempus. Suspendisse potenti. Praesent nec ornare quam. Etiam fringilla hendrerit nulla. Proin fermentum finibus dui ut dapibus. Aliquam mattis interdum lacus, nec interdum justo interdum ut. Aliquam sagittis turpis eu magna egestas, et placerat arcu aliquet. In vel feugiat dolor. Quisque efficitur tristique ligula ut dictum. Aenean consectetur nunc a turpis vestibulum semper. Donec non ultricies ligula, non suscipit felis. Aenean vel orci ultrices metus scelerisque sagittis ut eu massa. Pellentesque consectetur, ex scelerisque porttitor volutpat, felis neque aliquet sapien, tristique efficitur arcu enim luctus enim.',

];